spring:
  application:
    name: flagly-api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082
